{
  parserClass="com.github.xepozz.gitattributes.language.parser.GitattributesParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Gitattributes"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.xepozz.gitattributes.language.psi"
  psiImplPackage="com.github.xepozz.gitattributes.language.psi.impl"

  elementTypeHolderClass="com.github.xepozz.gitattributes.language.psi.GitattributesTypes"
  elementTypeClass="com.github.xepozz.gitattributes.language.psi.GitattributesElementType"
  tokenTypeClass="com.github.xepozz.gitattributes.language.psi.GitattributesTokenType"

//  psiImplUtilClass="com.github.xepozz.gitattributes.language.psi.impl.GitattributesImplUtil"
}

gitattributesFile ::= item_*

private item_ ::= (definition | COMMENT | EOL)

definition ::= unary_definition
unary_definition ::= pattern attributeList
pattern ::= TEXT
attributeList ::= attribute+
attribute ::= DASH? TEXT (EQUALS_SIGN TEXT)?
{
    implements=["com.intellij.psi.NavigatablePsiElement"]
    extends="com.github.xepozz.gitattributes.language.psi.impl.AttributesAttributeBaseImpl"
}

//cronExpression ::= (SCHEDULE COMMAND)
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//}
//
//variableDefinition ::= (VARIABLE_NAME EQUAL_SIGN VARIABLE_VALUE)
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitattributes.language.psi.impl.GitattributesVariableBaseImpl"
//}
//VARIABLE_NAME ::= IDENTIFIER
//VARIABLE_VALUE ::= CONTENT
//
//SCHEDULE ::= TIME_POINTER TIME_POINTER TIME_POINTER TIME_POINTER TIME_POINTER
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitattributes.language.psi.impl.GitattributesScheduleBaseImpl"
//}
//
//TIME_POINTER ::= TIME_LIST
//TIME_LIST ::= TIME_LIST_ITEM (COMMA TIME_LIST_ITEM)*
//
//TIME_LIST_ITEM ::= TIME_RANGE_STEP | TIME_RANGE | TIME_EXACT | TIME_ANY
//
//TIME_RANGE_STEP ::= (TIME_RANGE | TIME_EXACT | TIME_ANY) SLASH NUMBER
//{
//    pin=2
//}
//
//TIME_RANGE ::= NUMBER HYPHEN NUMBER
//{
//    pin=2
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitattributes.language.psi.impl.GitattributesTimeRangeBaseImpl"
//    methods=[getFirst getSecond getIntRange]
//}
//TIME_ANY ::= STAR
//TIME_EXACT ::= NUMBER
//
//COMMAND ::= CONTENT
//{
//    implements=["com.intellij.psi.NavigatablePsiElement" "com.intellij.psi.PsiLanguageInjectionHost"]
//    extends="com.github.xepozz.gitattributes.language.psi.impl.GitattributesAttributeBaseImplpl"
//}

COMMENT ::= SINGLE_COMMENT
